baseURL = 'https://rmb122.com/'
languageCode = 'zh-cn'
title = "rmb122's notebook"
theme = "archie"
copyright = "rmb122"
pygmentsStyle = "dracula"
pygmentsCodeFences = true
pygmentsCodeFencesguesssyntax = true
pygmentsOptions = "linenos=inline"
disablePathToLower = true
googleAnalytics = 'G-1MH3QGWHV5'

[permalinks]
posts = '/:year/:month/:day/:filename/'

[author]
name = "rmb122"

[params]
description = "rmb122's notebook"
mode = "toggle" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.

[[menu.main]]
name = "首页"
url = "/"
weight = 1
post = '&nbsp;'

[[menu.main]]
name = "归档"
url = "/posts"
weight = 2
post = '&nbsp;'

[[menu.main]]
name = "标签"
url = "/tags"
weight = 3
post = '&nbsp;'

[[menu.main]]
name = "友链"
url = "/links"
weight = 4
post = '&nbsp;'

[[menu.main]]
name = "关于"
url = "/about"
weight = 5

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rmb122"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://rmb122.com/index.xml"